services:
    mariadb:
        container_name: mariadb
        volumes:
            - mariadb:/var/lib/mysql
        build: ./requirements/mariadb
        networks:
            - inception
        env_file:
            - .env
        restart: always
    wordpress:
        container_name: wordpress
        volumes:
            - wordpress:/var/www/wordpress
        build: ./requirements/wordpress
        networks:
            - inception
        env_file:
            - .env
        depends_on:
            - mariadb
        restart: always
    nginx:
        container_name: nginx
        volumes:
            - wordpress:/var/www/wordpress
        build: ./requirements/nginx
        networks:
            - inception
        env_file:
            - .env
        depends_on:
            - wordpress
        ports:
            - 443:443
        restart: always

networks:
    inception:
      driver: bridge

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/aaoutem-/data/wordpressvolume
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/aaoutem-/data/mariadbvolume
